# permissions for end users to view ccloudenvironments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ccloudenvironment-viewer-role
rules:
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudenvironments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudenvironments/status
  verbs:
  - get
