# permissions for end users to view ccloudkafkas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ccloudkafka-viewer-role
rules:
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudkafkas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudkafkas/status
  verbs:
  - get
