# permissions for end users to edit ccloudenvironments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ccloudenvironment-editor-role
rules:
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudenvironments/status
  verbs:
  - get
