# permissions for end users to edit ccloudkafkas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ccloudkafka-editor-role
rules:
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudkafkas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudkafkas/status
  verbs:
  - get
