---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudenvironments/finalizers
  verbs:
  - update
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudenvironments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudkafkas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudkafkas/finalizers
  verbs:
  - update
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudkafkas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudschemaregistries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudschemaregistries/finalizers
  verbs:
  - update
- apiGroups:
  - messages.kubbee.tech
  resources:
  - ccloudschemaregistries/status
  verbs:
  - get
  - patch
  - update
