# permissions for end users to view setupkafkas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: setupkafka-viewer-role
rules:
- apiGroups:
  - messages.kubbee.tech
  resources:
  - setupkafkas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - messages.kubbee.tech
  resources:
  - setupkafkas/status
  verbs:
  - get
