# permissions for end users to view setupenvironments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: setupenvironment-viewer-role
rules:
- apiGroups:
  - messages.kubbee.tech
  resources:
  - setupenvironments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - messages.kubbee.tech
  resources:
  - setupenvironments/status
  verbs:
  - get
