//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Kubbee Tech.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudEnvironment) DeepCopyInto(out *CCloudEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudEnvironment.
func (in *CCloudEnvironment) DeepCopy() *CCloudEnvironment {
	if in == nil {
		return nil
	}
	out := new(CCloudEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CCloudEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudEnvironmentList) DeepCopyInto(out *CCloudEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CCloudEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudEnvironmentList.
func (in *CCloudEnvironmentList) DeepCopy() *CCloudEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(CCloudEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CCloudEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudEnvironmentResource) DeepCopyInto(out *CCloudEnvironmentResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudEnvironmentResource.
func (in *CCloudEnvironmentResource) DeepCopy() *CCloudEnvironmentResource {
	if in == nil {
		return nil
	}
	out := new(CCloudEnvironmentResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudEnvironmentSpec) DeepCopyInto(out *CCloudEnvironmentSpec) {
	*out = *in
	out.CCloudEnvironmentResource = in.CCloudEnvironmentResource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudEnvironmentSpec.
func (in *CCloudEnvironmentSpec) DeepCopy() *CCloudEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(CCloudEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudEnvironmentStatus) DeepCopyInto(out *CCloudEnvironmentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudEnvironmentStatus.
func (in *CCloudEnvironmentStatus) DeepCopy() *CCloudEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(CCloudEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudKafka) DeepCopyInto(out *CCloudKafka) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudKafka.
func (in *CCloudKafka) DeepCopy() *CCloudKafka {
	if in == nil {
		return nil
	}
	out := new(CCloudKafka)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CCloudKafka) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudKafkaDedicate) DeepCopyInto(out *CCloudKafkaDedicate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudKafkaDedicate.
func (in *CCloudKafkaDedicate) DeepCopy() *CCloudKafkaDedicate {
	if in == nil {
		return nil
	}
	out := new(CCloudKafkaDedicate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudKafkaList) DeepCopyInto(out *CCloudKafkaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CCloudKafka, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudKafkaList.
func (in *CCloudKafkaList) DeepCopy() *CCloudKafkaList {
	if in == nil {
		return nil
	}
	out := new(CCloudKafkaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CCloudKafkaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudKafkaResource) DeepCopyInto(out *CCloudKafkaResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudKafkaResource.
func (in *CCloudKafkaResource) DeepCopy() *CCloudKafkaResource {
	if in == nil {
		return nil
	}
	out := new(CCloudKafkaResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudKafkaSpec) DeepCopyInto(out *CCloudKafkaSpec) {
	*out = *in
	out.CCloudKafkaDedicate = in.CCloudKafkaDedicate
	out.CCloudKafkaResource = in.CCloudKafkaResource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudKafkaSpec.
func (in *CCloudKafkaSpec) DeepCopy() *CCloudKafkaSpec {
	if in == nil {
		return nil
	}
	out := new(CCloudKafkaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudKafkaStatus) DeepCopyInto(out *CCloudKafkaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudKafkaStatus.
func (in *CCloudKafkaStatus) DeepCopy() *CCloudKafkaStatus {
	if in == nil {
		return nil
	}
	out := new(CCloudKafkaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudSchemaRegistry) DeepCopyInto(out *CCloudSchemaRegistry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudSchemaRegistry.
func (in *CCloudSchemaRegistry) DeepCopy() *CCloudSchemaRegistry {
	if in == nil {
		return nil
	}
	out := new(CCloudSchemaRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CCloudSchemaRegistry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudSchemaRegistryList) DeepCopyInto(out *CCloudSchemaRegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CCloudSchemaRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudSchemaRegistryList.
func (in *CCloudSchemaRegistryList) DeepCopy() *CCloudSchemaRegistryList {
	if in == nil {
		return nil
	}
	out := new(CCloudSchemaRegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CCloudSchemaRegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudSchemaRegistryResource) DeepCopyInto(out *CCloudSchemaRegistryResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudSchemaRegistryResource.
func (in *CCloudSchemaRegistryResource) DeepCopy() *CCloudSchemaRegistryResource {
	if in == nil {
		return nil
	}
	out := new(CCloudSchemaRegistryResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudSchemaRegistrySpec) DeepCopyInto(out *CCloudSchemaRegistrySpec) {
	*out = *in
	out.CCloudSchemaRegistryResource = in.CCloudSchemaRegistryResource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudSchemaRegistrySpec.
func (in *CCloudSchemaRegistrySpec) DeepCopy() *CCloudSchemaRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(CCloudSchemaRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCloudSchemaRegistryStatus) DeepCopyInto(out *CCloudSchemaRegistryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCloudSchemaRegistryStatus.
func (in *CCloudSchemaRegistryStatus) DeepCopy() *CCloudSchemaRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(CCloudSchemaRegistryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}
